#mode用于指定测试的模式：
#predict          表示单张图片预测
#video            表示视频检测
#fps              表示测试fps
mode: "predict"
#video_path       用于指定视频的路径，当video_path=0时表示检测摄像头
#video_save_path  表示视频保存的路径，当video_save_path=""时表示不保存
#video_fps        用于保存的视频的fps
# video_path、video_save_path和video_fps仅在mode='video'时有效
video_path: 0
video_save_path: ""
video_fps: 25.0